version: "3.9"
services:
  app:
    build: .
    container_name: gym_app
    ports:
      - "5002:5002"

    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      JWT_SECRET_KEY: 'gym_app'
      PORT: 5002
      NAME_APP: 'Gym_App'
      JWT_ACCESS_TOKEN_EXPIRES: 3600
      MAIL_SERVER: 'smtp.gmail.com'
      MAIL_PORT: '587'
      MAIL_USE_TLS: 'True'
      MAIL_USERNAME: 'grupodmkn@gmail.com'
      MAIL_PASSWORD: 'oqfhpdjhbfcecdfg'
      FLASKY_MAIL_SENDER: 'GYM UM GrupoD <grupodmkn@gmail.com>'
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: gym_app 

    depends_on:
      db:
        condition: "service_healthy"

  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_app
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
